export const DUMMY_TUNE = {
  title: "mary had a little lamb",
  shuffledArray: [
    { note: 64, index: 0 },
    { note: 62, index: 9 },
    { note: 60, index: 12 },
    { note: 64, index: 10 },
    { note: 62, index: 3 },
    { note: 64, index: 6 },
    { note: 60, index: 2 },
    { note: 62, index: 11 },
    { note: 64, index: 7 },
    { note: 62, index: 1 },
    { note: 64, index: 4 },
    { note: 62, index: 8 },
    { note: 64, index: 5 },
  ],
  sortedArray: [
    { note: 64, index: 0 },
    { note: 62, index: 1 },
    { note: 60, index: 2 },
    { note: 62, index: 3 },
    { note: 64, index: 4 },
    { note: 64, index: 5 },
    { note: 64, index: 6 },
    { note: 64, index: 7 },
    { note: 62, index: 8 },
    { note: 62, index: 9 },
    { note: 64, index: 10 },
    { note: 62, index: 11 },
    { note: 60, index: 12 },
  ],
  remainingClues: 8,
};
